"""Protocol for all streaming platform clients."""

from typing import Protocol

from tuneshift.models import PlaylistInfo, TrackResult


class MusicPlatformClient(Protocol):
    """Protocol for all streaming platform operations."""

    @property
    def platform_name(self) -> str: ...

    def login(self) -> bool: ...
    def load_session(self) -> bool: ...
    def search_track(self, query: str, limit: int = 10) -> list[TrackResult]: ...
    def search_isrc(self, isrc: str) -> TrackResult | None: ...
    def get_playlist(self, playlist_id: str) -> PlaylistInfo | None: ...
    def get_playlist_tracks(self, playlist_id: str) -> list[TrackResult]: ...
    def create_playlist(self, name: str, description: str = "") -> PlaylistInfo: ...
    def add_tracks(self, playlist_id: str, track_ids: list[str]) -> int: ...
    def remove_tracks_by_positions(
        self, playlist_id: str, positions: list[int]
    ) -> int: ...
    def replace_playlist_tracks(
        self, playlist_id: str, track_ids: list[str]
    ) -> None: ...
    def find_playlist_by_name(self, name: str) -> PlaylistInfo | None: ...
